<a href="https://colab.research.google.com/github/TonyVM/parkinson-speech-analisys/blob/master/01-cleanData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
from sklearn.preprocessing import MinMaxScaler, normalize, StandardScaler, Normalizer
import pandas as pd

In [5]:
df = pd.read_csv('train-v1.2.csv')

In [7]:
df.head()

,id,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
0,1,1.488,0.000090,0.900,0.794,2.699,8.334,0.779,4.517,4.609,...,187.576,160,159,0.006065,0.000416,0.000,0,0.000,23,1
1,1,0.728,0.000038,0.353,0.376,1.059,5.864,0.642,2.058,3.180,...,234.505,170,169,0.005181,0.000403,2.247,0,0.000,23,1
2,1,1.220,0.000074,0.732,0.670,2.196,8.719,0.875,4.347,5.166,...,211.442,1431,1427,0.006071,0.000474,10.656,1,0.178,23,1
3,1,2.502,0.000123,1.156,1.634,3.469,13.513,1.273,5.263,8.771,...,220.230,94,92,0.004910,0.000320,0.000,0,0.000,23,1
4,1,3.509,0.000167,1.715,1.539,5.145,9.112,1.040,3.102,4.927,...,225.162,117,114,0.004757,0.000380,18.182,1,13.318,23,1

In [36]:
cols = df.columns[0:-1]
# X = df[cols]
# y = df['class information']

In [37]:
# X.head()

In [73]:
x_cols = df.columns[1:-1]
x_cols

Index(['Jitter (local)', 'Jitter (local, absolute)', 'Jitter (rap)',
       'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, dB)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NTH', 'HTN', 'Median pitch',
       'Mean pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks', 'UPDRS'],
      dtype='object')

In [56]:
std_scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[x_cols] = std_scaler.fit_transform(df_scaled[x_cols])

In [44]:
import pandas as pd

In [60]:
df_scaled.head()

,id,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
0,1,-0.675388,-0.753597,-0.354501,-0.487023,-0.354835,-0.841237,-0.990536,-0.392404,-0.697428,...,-0.389355,0.335138,0.355088,-0.257085,-0.589789,-1.320419,-0.702989,-0.816255,0.629441,1
1,1,-1.106178,-1.247145,-0.913239,-0.854272,-0.913222,-1.294483,-1.316829,-1.208336,-0.992764,...,-0.003054,0.401824,0.422047,-0.728418,-0.607475,-1.213241,-0.702989,-0.816255,0.629441,1
2,1,-0.827298,-0.905585,-0.526106,-0.595968,-0.526097,-0.770589,-0.761893,-0.448812,-0.582312,...,-0.192900,8.810982,8.845484,-0.253871,-0.509519,-0.812148,-0.083405,-0.804510,0.629441,1
3,1,-0.100625,-0.447111,-0.093007,0.250988,-0.092666,0.109111,0.186022,-0.144870,0.162744,...,-0.120560,-0.104993,-0.093537,-0.873122,-0.723287,-1.320419,-0.702989,-0.816255,0.629441,1
4,1,0.470171,-0.032621,0.477989,0.167522,0.477979,-0.698474,-0.368913,-0.861921,-0.631706,...,-0.079962,0.048386,0.053773,-0.954633,-0.639988,-0.453173,-0.083405,0.062552,0.629441,1

In [59]:
# df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
# df_scaled.head()

In [61]:
# df_scaled.head()

In [62]:
df_scaled = df_scaled.groupby('id').mean()
df_scaled['class information'] = df_scaled['class information'].apply(int)
df_scaled.head()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
id,,,,,,,,,,,,,,,,,,,,,
1,-0.204093,-0.525192,-0.141762,-0.075237,-0.141760,-0.434911,-0.304058,-0.501009,-0.344320,-0.053068,...,-0.067066,0.411827,0.424623,-0.814377,-0.574694,-0.494374,-0.250216,-0.365837,0.629441,1
2,0.004827,0.416246,0.028311,0.092268,0.028283,-0.100411,-0.030255,-0.053736,-0.174999,0.080500,...,-0.583957,0.077369,0.087510,0.775826,-0.295884,-0.856772,-0.154896,-0.441886,-0.314721,1
3,0.185296,-0.366871,0.392265,0.299411,0.392139,0.777553,0.714209,0.801592,0.615606,0.513985,...,0.602992,-0.026508,-0.027608,-1.068311,-0.109752,0.354171,-0.011915,0.105375,1.699492,1
4,-0.643057,-1.009431,-0.449732,-0.456442,-0.449855,-0.416723,-0.427723,-0.194170,-0.271007,-0.517578,...,0.313472,0.423369,0.434409,-1.297653,-0.773693,-0.771218,-0.154896,-0.097378,-0.503553,1
5,0.039722,0.748963,-0.012352,-0.064248,-0.012367,0.371927,0.414760,0.513396,0.324412,0.544729,...,-0.591611,-0.359171,-0.349526,1.316400,0.170965,-0.181484,-0.059575,-0.060304,0.188832,1

In [55]:
normalizer = Normalizer()
df_norm = df.copy()
df_norm[x_cols] = normalizer.fit_transform(df_norm[x_cols])

In [ ]:
df_norm = df_norm.groupby('id').mean()
df_norm['class information'] = df_norm['class information'].apply(int)
df_norm.head()

In [74]:
minmax_scaler = MinMaxScaler()
df_minmax = df.copy()

In [75]:
df_minmax[x_cols] = minmax_scaler.fit_transform(df_minmax[x_cols])

In [76]:
df_minmax.head()

,id,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
0,1,0.091499,0.108709,0.105356,0.052968,0.105351,0.178940,0.258212,0.158782,0.054066,...,0.199119,0.107383,0.106783,0.401347,0.057147,0.000000,0.000000,0.000000,0.407407,1
1,1,0.037925,0.040518,0.036585,0.021915,0.036626,0.117116,0.205882,0.061681,0.034261,...,0.290699,0.114094,0.113499,0.313279,0.055123,0.025488,0.000000,0.000000,0.407407,1
2,1,0.072607,0.087709,0.084234,0.043756,0.084273,0.188576,0.294882,0.152069,0.061786,...,0.245693,0.960403,0.958361,0.401948,0.066332,0.120874,0.083333,0.002575,0.407407,1
3,1,0.162978,0.151055,0.137541,0.115370,0.137619,0.308570,0.446906,0.188240,0.111750,...,0.262842,0.063087,0.061786,0.286241,0.041870,0.000000,0.000000,0.000000,0.407407,1
4,1,0.233963,0.208323,0.207820,0.108313,0.207853,0.198413,0.357907,0.102906,0.058474,...,0.272467,0.078523,0.076561,0.271011,0.051402,0.206243,0.083333,0.192688,0.407407,1

In [79]:
df_minmax[x_cols].describe()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Minimum pitch,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS
count,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,...,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000
mean,0.175492,0.212830,0.148988,0.094148,0.149024,0.293687,0.417072,0.205481,0.100836,0.264387,...,0.173331,0.291423,0.073654,0.071168,0.449384,0.124636,0.314014,0.094551,0.178973,0.222222
std,0.124422,0.138232,0.123141,0.084596,0.123138,0.136469,0.160455,0.119064,0.067093,0.135970,...,0.122507,0.237185,0.100690,0.100347,0.186940,0.114485,0.237928,0.134564,0.219366,0.294347
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.092873,0.114829,0.069776,0.043440,0.069847,0.204458,0.320092,0.126639,0.061707,0.170916,...,0.085637,0.113400,0.028691,0.027367,0.299099,0.055269,0.092439,0.000000,0.000000,0.000000
50%,0.155505,0.188126,0.122391,0.077669,0.122449,0.279423,0.411956,0.183166,0.087905,0.246382,...,0.154428,0.215501,0.043624,0.041639,0.443183,0.093164,0.300608,0.083333,0.084292,0.037037
75%,0.227090,0.289350,0.193676,0.119883,0.193752,0.358136,0.499618,0.254541,0.122671,0.334240,...,0.238744,0.347865,0.075839,0.073203,0.586616,0.146332,0.488489,0.083333,0.321997,0.412037
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000