<a href="https://colab.research.google.com/github/TonyVM/parkinson-speech-analisys/blob/master/01_clean_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
from sklearn.preprocessing import MinMaxScaler, normalize, StandardScaler, Normalizer
import pandas as pd

In [103]:
df = pd.read_csv('train-v1.2.csv')

In [105]:
df.describe()

,id,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
count,1040.00000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,...,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000
mean,20.50000,2.679523,0.000170,1.247053,1.348327,3.741161,12.918391,1.194895,5.699600,7.983552,...,234.875990,109.744231,105.969231,0.006547,0.000843,27.682856,1.134615,12.370042,13.000000,0.500000
std,11.54895,1.765053,0.000106,0.979462,1.138742,2.938443,5.452204,0.420071,3.015183,4.840892,...,121.541243,150.027703,149.417074,0.001875,0.000723,20.975294,1.614764,15.161916,15.894745,0.500241
min,1.00000,0.190000,0.000006,0.062000,0.081000,0.185000,1.185000,0.103000,0.496000,0.708000,...,85.541000,0.000000,0.000000,0.002039,0.000055,0.000000,0.000000,0.000000,1.000000,0.000000
25%,10.75000,1.507500,0.000095,0.617000,0.665750,1.851750,9.353500,0.941000,3.703000,5.160250,...,143.650750,42.750000,40.750000,0.005039,0.000404,8.149250,0.000000,0.000000,1.000000,0.000000
50%,20.50000,2.396000,0.000151,1.035500,1.126500,3.107000,12.348500,1.181500,5.134500,7.050500,...,195.971000,65.000000,62.000000,0.006484,0.000644,26.501000,1.000000,5.826000,3.000000,0.500000
75%,30.25000,3.411500,0.000229,1.602500,1.694750,4.808500,15.493250,1.411000,6.942000,9.558930,...,263.798250,113.000000,109.000000,0.007923,0.000980,43.064250,1.000000,22.255500,23.250000,1.000000
max,40.00000,14.376000,0.000777,8.016000,13.542000,24.048000,41.137000,2.721000,25.820000,72.860000,...,597.974000,1490.000000,1489.000000,0.012070,0.006371,88.158000,12.000000,69.117000,55.000000,1.000000

In [37]:
# X.head()

## **Columnas**

In [107]:
x_cols = df.columns[1:-1]
x_cols

Index(['Jitter (local)', 'Jitter (local, absolute)', 'Jitter (rap)',
       'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, dB)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NTH', 'HTN', 'Median pitch',
       'Mean pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks', 'UPDRS'],
      dtype='object')

## Standard Scaler

In [110]:
std_scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[x_cols] = std_scaler.fit_transform(df_scaled[x_cols])

In [111]:
df_scaled.head()

,id,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
0,1,-0.675388,-0.753597,-0.354501,-0.487023,-0.354835,-0.841237,-0.990536,-0.392404,-0.697428,...,-0.389355,0.335138,0.355088,-0.257085,-0.589789,-1.320419,-0.702989,-0.816255,0.629441,1
1,1,-1.106178,-1.247145,-0.913239,-0.854272,-0.913222,-1.294483,-1.316829,-1.208336,-0.992764,...,-0.003054,0.401824,0.422047,-0.728418,-0.607475,-1.213241,-0.702989,-0.816255,0.629441,1
2,1,-0.827298,-0.905585,-0.526106,-0.595968,-0.526097,-0.770589,-0.761893,-0.448812,-0.582312,...,-0.192900,8.810982,8.845484,-0.253871,-0.509519,-0.812148,-0.083405,-0.804510,0.629441,1
3,1,-0.100625,-0.447111,-0.093007,0.250988,-0.092666,0.109111,0.186022,-0.144870,0.162744,...,-0.120560,-0.104993,-0.093537,-0.873122,-0.723287,-1.320419,-0.702989,-0.816255,0.629441,1
4,1,0.470171,-0.032621,0.477989,0.167522,0.477979,-0.698474,-0.368913,-0.861921,-0.631706,...,-0.079962,0.048386,0.053773,-0.954633,-0.639988,-0.453173,-0.083405,0.062552,0.629441,1

In [112]:
df_scaled.describe()

,id,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
count,1040.00000,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,...,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1.040000e+03,1040.000000,1040.000000
mean,20.50000,1.639714e-16,-1.229786e-16,-6.832142e-18,1.024821e-16,6.148928e-17,1.058982e-16,-2.527892e-16,-6.832142e-17,-7.173749e-17,...,1.503071e-16,2.049643e-17,5.465713e-17,1.776357e-16,-9.906605e-17,1.229786e-16,4.099285e-17,2.732857e-17,0.000000,0.500000
std,11.54895,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,...,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481e+00,1.000481,0.500241
min,1.00000,-1.411131e+00,-1.540398e+00,-1.210484e+00,-1.113454e+00,-1.210802e+00,-2.153081e+00,-2.600563e+00,-1.726630e+00,-1.503659e+00,...,-1.229269e+00,-7.318450e-01,-7.095589e-01,-2.405051e+00,-1.089192e+00,-1.320419e+00,-7.029890e-01,-8.162553e-01,-0.755330,0.000000
25%,10.75000,-6.643352e-01,-7.093028e-01,-6.435737e-01,-5.997017e-01,-6.433068e-01,-6.541585e-01,-6.047014e-01,-6.625008e-01,-5.835000e-01,...,-7.509314e-01,-4.467606e-01,-4.367012e-01,-8.043048e-01,-6.061988e-01,-9.317154e-01,-7.029890e-01,-8.162553e-01,-0.755330,0.000000
50%,20.50000,-1.607086e-01,-1.788011e-01,-2.160927e-01,-1.948939e-01,-2.159193e-01,-1.045751e-01,-3.190337e-02,-1.875084e-01,-1.928365e-01,...,-3.202510e-01,-2.983833e-01,-2.944134e-01,-3.318419e-02,-2.750293e-01,-5.637224e-02,-8.340547e-02,-4.318182e-01,-0.629441,0.500000
75%,30.25000,4.149052e-01,5.538284e-01,3.630750e-01,3.043618e-01,3.634075e-01,4.724875e-01,5.146960e-01,4.122462e-01,3.255879e-01,...,2.380770e-01,2.171156e-02,2.029371e-02,7.344518e-01,1.896027e-01,7.336629e-01,-8.340547e-02,6.523063e-01,0.645177,1.000000
max,40.00000,6.629890e+00,5.697281e+00,6.914208e+00,1.071317e+01,6.914073e+00,5.178124e+00,3.634718e+00,6.676239e+00,1.340820e+01,...,2.988884e+00,9.204432e+00,9.260630e+00,2.946838e+00,7.649798e+00,2.884548e+00,6.732013e+00,3.744531e+00,2.643654,1.000000

In [59]:
# df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
# df_scaled.head()

In [61]:
# df_scaled.head()

In [117]:
df_scaled = df_scaled.groupby('id').mean()
df_scaled['class information'] = df_scaled['class information'].apply(int)
df_scaled.head()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
id,,,,,,,,,,,,,,,,,,,,,
1,-0.204093,-0.525192,-0.141762,-0.075237,-0.141760,-0.434911,-0.304058,-0.501009,-0.344320,-0.053068,...,-0.067066,0.411827,0.424623,-0.814377,-0.574694,-0.494374,-0.250216,-0.365837,0.629441,1
2,0.004827,0.416246,0.028311,0.092268,0.028283,-0.100411,-0.030255,-0.053736,-0.174999,0.080500,...,-0.583957,0.077369,0.087510,0.775826,-0.295884,-0.856772,-0.154896,-0.441886,-0.314721,1
3,0.185296,-0.366871,0.392265,0.299411,0.392139,0.777553,0.714209,0.801592,0.615606,0.513985,...,0.602992,-0.026508,-0.027608,-1.068311,-0.109752,0.354171,-0.011915,0.105375,1.699492,1
4,-0.643057,-1.009431,-0.449732,-0.456442,-0.449855,-0.416723,-0.427723,-0.194170,-0.271007,-0.517578,...,0.313472,0.423369,0.434409,-1.297653,-0.773693,-0.771218,-0.154896,-0.097378,-0.503553,1
5,0.039722,0.748963,-0.012352,-0.064248,-0.012367,0.371927,0.414760,0.513396,0.324412,0.544729,...,-0.591611,-0.359171,-0.349526,1.316400,0.170965,-0.181484,-0.059575,-0.060304,0.188832,1

## Normalizer

In [118]:
normalizer = Normalizer()
df_norm = df.copy()
df_norm[x_cols] = normalizer.fit_transform(df_norm[x_cols])

In [125]:
df_norm = df_norm.groupby('id').mean()
df_norm['class information'] = df_norm['class information'].apply(int)
df_norm.head()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
id,,,,,,,,,,,,,,,,,,,,,
1,0.005148,2.542276e-07,0.002455,0.002804,0.007365,0.023214,0.002351,0.009190,0.013903,0.026123,...,0.498804,0.283792,0.279353,0.000011,9.273478e-07,0.037450,0.001508,0.014249,0.050828,1
2,0.009227,7.404196e-07,0.004341,0.004930,0.013024,0.040775,0.003914,0.018137,0.023466,0.042289,...,0.500730,0.285869,0.279344,0.000027,2.095272e-06,0.034633,0.002398,0.018561,0.026526,1
3,0.005743,2.551149e-07,0.003131,0.003236,0.009391,0.033993,0.002973,0.016140,0.021637,0.030691,...,0.586883,0.211189,0.204170,0.000009,1.383699e-06,0.068788,0.002099,0.026967,0.080299,1
4,0.002810,1.152450e-07,0.001468,0.001507,0.004403,0.019521,0.001858,0.009383,0.012212,0.016566,...,0.492888,0.289099,0.284868,0.000008,5.096581e-07,0.021099,0.001543,0.019728,0.009108,1
5,0.010613,9.859928e-07,0.004732,0.004816,0.014196,0.057658,0.005297,0.027973,0.036913,0.060877,...,0.561436,0.196473,0.189064,0.000036,3.317278e-06,0.092949,0.003313,0.040972,0.062113,1

In [128]:
df_norm[x_cols].describe()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Minimum pitch,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS
count,40.000000,4.000000e+01,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,...,40.000000,40.000000,40.000000,40.000000,40.000000,4.000000e+01,40.000000,40.000000,40.000000,40.000000
mean,0.007301,5.111107e-07,0.003351,0.003631,0.010052,0.035927,0.003331,0.015749,0.021936,0.034533,...,0.346686,0.559299,0.224589,0.216438,0.000020,2.178169e-06,0.076890,0.002696,0.031115,0.036546
std,0.002603,2.740849e-07,0.001404,0.001481,0.004211,0.011377,0.000953,0.005572,0.007867,0.012666,...,0.033734,0.045848,0.041617,0.043425,0.000010,9.381421e-07,0.030259,0.000787,0.011105,0.046994
min,0.002674,1.152450e-07,0.001002,0.001111,0.003007,0.014293,0.001468,0.005500,0.007179,0.011883,...,0.282570,0.492888,0.115808,0.097801,0.000008,5.096581e-07,0.021099,0.001304,0.014249,0.001782
25%,0.005596,2.538176e-07,0.002316,0.002780,0.006950,0.028504,0.002681,0.011670,0.016361,0.025649,...,0.330729,0.527931,0.203777,0.190386,0.000011,1.358241e-06,0.059960,0.002091,0.023113,0.002567
50%,0.006848,4.683076e-07,0.003127,0.003270,0.009382,0.036319,0.003380,0.015962,0.021753,0.031755,...,0.350658,0.544671,0.222684,0.216155,0.000017,2.195733e-06,0.075791,0.002668,0.028348,0.006508
75%,0.009259,7.421727e-07,0.004328,0.004525,0.012984,0.045530,0.004203,0.019159,0.027118,0.042336,...,0.372066,0.588855,0.244365,0.239643,0.000026,2.602996e-06,0.088769,0.003278,0.038210,0.061855
max,0.014983,1.155741e-06,0.007947,0.008384,0.023842,0.057658,0.005297,0.027973,0.038242,0.063354,...,0.398865,0.653188,0.308985,0.300421,0.000038,5.375419e-06,0.179870,0.004277,0.057878,0.185675

## Normalizacion por MinMax

In [121]:
minmax_scaler = MinMaxScaler()
df_minmax = df.copy()

In [129]:
df_minmax[x_cols] = minmax_scaler.fit_transform(df_minmax[x_cols])

In [130]:
df_minmax = df_minmax.groupby('id').mean()
df_minmax['class information'] = df_minmax['class information'].apply(int)
df_minmax.head()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
id,,,,,,,,,,,,,,,,,,,,,
1,0.230928,0.185973,0.225782,0.269134,0.225782,0.174708,0.231221,0.149200,0.162180,0.369132,...,0.376593,0.680674,0.691799,0.171114,0.078950,0.184454,0.090909,0.080032,0.407407,1
2,0.324918,0.535338,0.291677,0.346151,0.291667,0.275725,0.317774,0.299309,0.213633,0.420918,...,0.118302,0.387640,0.403219,0.734158,0.189564,0.000000,0.212121,0.000000,0.129630,1
3,0.406108,0.244726,0.432690,0.441394,0.432644,0.540866,0.553107,0.586364,0.453884,0.588985,...,0.711421,0.296629,0.304674,0.081203,0.263410,0.616348,0.393939,0.575922,0.722222,1
4,0.033445,0.006274,0.106460,0.093860,0.106409,0.180201,0.192129,0.252178,0.184458,0.189036,...,0.566748,0.690787,0.700176,0.000000,0.000000,0.043545,0.212121,0.362550,0.074074,1
5,0.340617,0.658808,0.275922,0.274187,0.275917,0.418369,0.458448,0.489643,0.365396,0.600905,...,0.114477,0.005169,0.029101,0.925560,0.374780,0.343709,0.333333,0.401566,0.277778,1

In [132]:
df_minmax[x_cols].describe()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Minimum pitch,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,...,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.322747,0.380870,0.280708,0.303727,0.280708,0.306049,0.327338,0.317343,0.266813,0.389707,...,0.402521,0.410105,0.319854,0.328307,0.459461,0.306952,0.436082,0.409091,0.465028,0.222222
std,0.204604,0.220031,0.196008,0.202673,0.196010,0.213940,0.207226,0.231497,0.207076,0.199001,...,0.257436,0.266795,0.249095,0.244888,0.313887,0.189540,0.243628,0.256212,0.294525,0.297954
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.189012,0.231131,0.162944,0.176424,0.162934,0.184897,0.225336,0.176274,0.161721,0.267367,...,0.191497,0.185745,0.116629,0.137897,0.170066,0.185866,0.254045,0.234848,0.220780,0.000000
50%,0.308289,0.320020,0.252770,0.273540,0.252791,0.253052,0.288947,0.264755,0.211163,0.364781,...,0.344424,0.406471,0.286404,0.298832,0.402167,0.281058,0.408832,0.333333,0.419746,0.037037
75%,0.407999,0.539936,0.334746,0.395936,0.334783,0.352105,0.357481,0.342488,0.289130,0.477321,...,0.605186,0.565768,0.457865,0.455302,0.712424,0.421737,0.616841,0.606061,0.686767,0.412037
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [134]:
df_minmax.to_csv('train_minmax_scaled.csv')
df_norm.to_csv('train_norm_scaled.csv')
df_scaled.to_csv('train_scaled.csv')

===========================

## importaciones para dividir en entrenamiento y prueba y dividir el dataset en las variables predictoras y la predicha

In [142]:
from sklearn.model_selection import train_test_split

In [150]:
X = df_minmax[x_cols]
y = df_minmax['class information']

In [162]:
# X

In [163]:
df_minmax.describe()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS,class information
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,...,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000
mean,0.322747,0.380870,0.280708,0.303727,0.280708,0.306049,0.327338,0.317343,0.266813,0.389707,...,0.410105,0.319854,0.328307,0.459461,0.306952,0.436082,0.409091,0.465028,0.222222,0.50000
std,0.204604,0.220031,0.196008,0.202673,0.196010,0.213940,0.207226,0.231497,0.207076,0.199001,...,0.266795,0.249095,0.244888,0.313887,0.189540,0.243628,0.256212,0.294525,0.297954,0.50637
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,0.189012,0.231131,0.162944,0.176424,0.162934,0.184897,0.225336,0.176274,0.161721,0.267367,...,0.185745,0.116629,0.137897,0.170066,0.185866,0.254045,0.234848,0.220780,0.000000,0.00000
50%,0.308289,0.320020,0.252770,0.273540,0.252791,0.253052,0.288947,0.264755,0.211163,0.364781,...,0.406471,0.286404,0.298832,0.402167,0.281058,0.408832,0.333333,0.419746,0.037037,0.50000
75%,0.407999,0.539936,0.334746,0.395936,0.334783,0.352105,0.357481,0.342488,0.289130,0.477321,...,0.565768,0.457865,0.455302,0.712424,0.421737,0.616841,0.606061,0.686767,0.412037,1.00000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

## Creando los grupos de entrenamiento y validacion

In [153]:
X_train, X_val, y_train, y_val = train_test_split(X, y, train_size=0.75, test_size=0.25)

In [160]:
X_train.head()

,Jitter (local),"Jitter (local, absolute)",Jitter (rap),Jitter (ppq5),Jitter (ddp),Shimmer (local),"Shimmer (local, dB)",Shimmer (apq3),Shimmer (apq5),Shimmer (apq11),...,Minimum pitch,Maximum pitch,Number of pulses,Number of periods,Mean period,Standard deviation of period,Fraction of locally unvoiced frames,Number of voice breaks,Degree of voice breaks,UPDRS
id,,,,,,,,,,,,,,,,,,,,,
1,0.230928,0.185973,0.225782,0.269134,0.225782,0.174708,0.231221,0.149200,0.162180,0.369132,...,0.615027,0.376593,0.680674,0.691799,0.171114,0.078950,0.184454,0.090909,0.080032,0.407407
12,0.841533,1.000000,0.785177,0.834048,0.785197,0.462872,0.490097,0.445383,0.414249,0.821295,...,0.239113,0.231415,0.458202,0.472222,0.663487,0.314161,0.407266,0.242424,0.183982,0.574074
39,0.174699,0.204599,0.206436,0.192272,0.206415,0.191165,0.197689,0.225799,0.184074,0.189482,...,0.532045,0.270482,0.163146,0.182981,0.268313,0.112545,0.490318,0.242424,0.751990,0.000000
8,0.204623,0.308184,0.195278,0.185420,0.195273,0.253631,0.297649,0.281521,0.221107,0.271445,...,0.301848,0.164094,0.213933,0.235450,0.512223,0.194051,0.467277,0.000000,0.210984,0.351852
38,0.248083,0.319187,0.129521,0.176673,0.129490,0.203772,0.224967,0.211613,0.160346,0.231929,...,0.248908,0.480768,0.457753,0.464065,0.434151,0.449046,0.618319,0.636364,0.475431,0.000000

In [161]:
y_train.head()

id
1     1
12    1
39    0
8     1
38    0
Name: class information, dtype: int64